/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modul7;

import javax.swing.JOptionPane;

/**
 *
 * @author Luviana
 */
public class form_beratbadan extends javax.swing.JFrame {

    /**
     * Creates new form form_beratbadan
     */
    public form_beratbadan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpJK = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTinggi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSaran = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rbPerempuan = new javax.swing.JRadioButton();
        rbLaki = new javax.swing.JRadioButton();
        btnKeluar = new javax.swing.JButton();
        btnHitung = new javax.swing.JButton();
        btnCoba = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtBerat = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtIdeal = new javax.swing.JTextField();
        txtHasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CEK IDEAL TUBUH");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1, 10, 380, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 60, 75, 30);

        txtNama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtNama);
        txtNama.setBounds(140, 60, 180, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("Tinggi");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 100, 75, 30);

        txtTinggi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtTinggi);
        txtTinggi.setBounds(140, 100, 50, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("kg");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 310, 30, 30);

        txtSaran.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtSaran);
        txtSaran.setBounds(10, 460, 360, 60);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Jenis Kelamin");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 180, 100, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setText("cm");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(200, 100, 75, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Hasil Diagnosa Kesehatan");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 360, 360, 30);

        btnGrpJK.add(rbPerempuan);
        rbPerempuan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbPerempuan.setText("Perempuan");
        getContentPane().add(rbPerempuan);
        rbPerempuan.setBounds(140, 180, 87, 30);

        btnGrpJK.add(rbLaki);
        rbLaki.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbLaki.setText("Laki-laki");
        getContentPane().add(rbLaki);
        rbLaki.setBounds(250, 180, 65, 30);

        btnKeluar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluar);
        btnKeluar.setBounds(260, 250, 75, 30);

        btnHitung.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
        getContentPane().add(btnHitung);
        btnHitung.setBounds(50, 250, 75, 30);

        btnCoba.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnCoba.setText("Coba Lagi");
        btnCoba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCoba);
        btnCoba.setBounds(150, 250, 90, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel8.setText("Berat Badan");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 140, 75, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel9.setText("kg");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(200, 140, 75, 30);

        txtBerat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtBerat);
        txtBerat.setBounds(140, 140, 50, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel10.setText("Berat badan ideal Anda adalah");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(50, 310, 190, 30);

        txtIdeal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtIdeal);
        txtIdeal.setBounds(240, 310, 50, 30);

        txtHasil.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtHasil);
        txtHasil.setBounds(10, 400, 360, 50);

        setBounds(0, 0, 395, 574);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        if ("".equals(txtNama.getText()) || "".equals(txtBerat.getText()) ||"".equals(txtTinggi.getText())) 
        { JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
        Double tinggi = Double.valueOf(txtTinggi.getText());
        Double berat = Double.valueOf(txtBerat.getText());
        Double hasil = null;
        
        if(rbLaki.isSelected()){
            hasil = (tinggi - 100) * 1;
        } else if (rbPerempuan.isSelected()){
            hasil = (tinggi -104) * 1;
        }
        
        String temp = Double.toString(hasil.intValue());
        
        if (hasil < berat) {
            txtIdeal.setText(temp);
            txtHasil.setText("Maaf " + txtNama.getText() + " , sepertinya anda overweight");
            txtSaran.setText("Banyaklah berolahraga dan hindari makanan berkolestrol");
        } else if (hasil > berat) {
            txtIdeal.setText(temp);
            txtHasil.setText("Maaf " + txtNama.getText() + " , sepertinya anda underweight");
            txtSaran.setText("Banyaklah mengkonsumsi makanan yang berkarbohidrat");
        } else {
            txtIdeal.setText(temp);
            txtHasil.setText("Hallo " + txtNama.getText() + " , berat badan Anda sudah ideal");
            txtSaran.setText("Lanjutkan pola makan teratur dan gaya hidup sehat");
        }
       }
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnCobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobaActionPerformed
        // TODO add your handling code here:
        
        txtNama.setText("");
        txtBerat.setText("");;
        txtTinggi.setText("");
        btnGrpJK.clearSelection();
        txtIdeal.setText("");
        txtHasil.setText("");
        txtSaran.setText("");
    }//GEN-LAST:event_btnCobaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_beratbadan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_beratbadan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_beratbadan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_beratbadan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_beratbadan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCoba;
    private javax.swing.ButtonGroup btnGrpJK;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.JTextField txtBerat;
    private javax.swing.JTextField txtHasil;
    private javax.swing.JTextField txtIdeal;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtSaran;
    private javax.swing.JTextField txtTinggi;
    // End of variables declaration//GEN-END:variables
}
